spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: 43.206.192.176:9092,43.206.192.176:9093,43.206.192.176:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: 43.206.192.176:9092,43.206.192.176:9093,43.206.192.176:9094
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092,dev:9093,dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer